### ISSUE TITLE
Wordpress Issue?

### ISSUE THREAD

**Issue by wm820** [peddleon/publisher-embed-examples#6] opened 2021-06-24 20:05 UTC
We tried to implement this on a Wordpress website.  When we click the "Offer Button", the form pops up for roughly two seconds and then closes.

**Comment by nickdandakis** [comment] 2021-06-24 20:09
hello @wm820, can you share some more information about your implementation?

Where did you inject the `<script/>` tag? And are you using a custom `target` for the button, or leaving `target` blank?

**Comment by wm820** [comment] 2021-06-24 20:25
We use the DIVI theme and played with some settings.  The popup seems to stay open now but we have an issue with the webpage Header blocking the top part of the popup.  The target for the button is left blank.

**Comment by nickdandakis** [comment] 2021-06-24 20:32
@wm820 is your site header blocking the top part of the popup due to a conflicting `z-index` value? If so, you can pass a custom `z-index` value as part of your `<script/>`'s `PeddlePublisherEmbedConfig` object like so:

```
<script>
PeddlePublisherEmbedConfig={publisherID:"YOUR_PUBLISHER_ID_HERE", zIndex:999999}
...
</script>
```

**Comment by wm820** [comment] 2021-06-24 20:53
Ok, the zIndex fixed the popup viewing issue, but now I am back to the popup disappearing after about two seconds.

**Comment by wm820** [comment] 2021-06-24 21:01
The popup seems to be reloading the page when opened.

**Comment by wm820** [comment] 2021-06-25 23:07
Any other solutions for the popup disappearing?

**Comment by nickdandakis** [comment] 2021-06-28 14:28
@wm820 can you send over your publisher ID? We'll have to take a look at your site to see if anything is conflicting. We tried to reproduce it, but couldn't.

**Comment by wm820** [comment] 2021-06-28 20:53
I actually gave up on the Wordpress implementation. It seems to have too many issues.  I got it working on an HTML website but wanted to know if the button can be used more than once on a page.  The button only shows in one area per page.

**Comment by nickdandakis** [comment] 2021-06-28 21:42
> I actually gave up on the Wordpress implementation. It seems to have too many issues. I got it working on an HTML website but wanted to know if the button can be used more than once on a page. The button only shows in one area per page.

Yes, you should be able to use the button more than once on a page. Pass in a class for a `target` instead of an id (e.g. `target: '.my-peddle-button'`) or programmatically call open/close (e.g. `PeddlePublisherEmbed('open')`)

**Comment by wm820** [comment] 2021-06-28 22:03
I'm somewhat knowledgeable of HTML/CSS but not an expert.  Where would I need to put the "target: '.my-peddle-button"

**Comment by nickdandakis** [comment] 2021-06-29 13:30
@wm820 in your `<script>` tag like so:

```
<script>
PeddlePublisherEmbedConfig={publisherID:"YOUR_PUBLISHER_ID_HERE", target: '.my-peddle-button'}
...
</script>
```

Going to close this issue since we can't reproduce, but please feel free to reach out to your account manager for support.

**Closed as completed by nickdandakis** 2021-06-29 13:30 UTC
